name: Submit production to Play Store

on:
  push:
    branches:
      - production
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code (tsc + ESLint)
        run: npm run lint

      - name: Run Jest tests
        run: npm test
  submit:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "npm"

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 22.5.0
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Call eas build
        run: eas build --profile production --platform android --auto-submit-with-profile production --non-interactive
