name: Test and Lint before pushing

on:
  push:
    branches:
      - staging
      - production
  pull_request:
    branches:
      - staging
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

#      - name: Lint code with ESLint
#        run: yarn lint

      - name: TypeScript check
        run: yarn tsc --noEmit

#      - name: Run Jest tests
#        run: yarn test --passWithNoTests
